### ISSUE TITLE
Using Jackson instead of gson

### ISSUE THREAD

**Issue by dongshengbc** [lightcouch/LightCouch#23]
Gson is chosen as the JSON serializer, but it seems Jackson is more and more popular.  

And I am wondering if it is possible to change to to Jackson? Or maybe give user the option?

**Comment by rama0120** [comment]
Do we have any updates here on this effort to decouple lightcouch from gson? We have a case of mixed libraries, Jackson and gson - as mentioned 2 years ago, Jackson is seeing a lot more Dev and growth than gson.

**Comment by lightcouch** [comment]
Closing this as won't fix.

LightCouch will continue to use Gson as its primary JSON/Java mapping.
Incorporating Jackson and Gson in the same repo appears not possible.
