### ISSUE TITLE
Bug with properties

### ISSUE THREAD

**Issue by romahuti2** [lightcouch/LightCouch#26]
I'm trying to run Spring MVC with lightcouch. And i have this error in log
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'couchDbClient' defined in ServletContext resource [/WEB-INF/mvc-dispatcher-servlet.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.lightcouch.CouchDbClient]: Constructor threw exception; nested exception is java.lang.IllegalStateException: Could not read configuration file from the classpath: couchdb.properties

I tried to copy couchdb.properties in every directory, but it didn't help

**Comment by Gramler** [comment]
What was the conclusion on this? I am using 0.1.6 and it is still showing this behaviour. Is this supposed to work or not?
Tx
Max
