### ISSUE TITLE
No support for special characters in document IDs

### ISSUE THREAD

**Issue by durera** [lightcouch/LightCouch#32]
EDIT: LightCouch doesn't seem to play nice if "/" is used in document IDs as when this ID is passed into URIBuilder as path(id) it assumes the intention is for the "/" to represent a path seperator and will not encode it as %2F in the resulting URI. 

See: http://wiki.apache.org/couchdb/HTTP_Document_API#Special_Fields

>Document IDs
>
>Document IDs don't have restrictions on what characters can be used. Although it should work, it is recommended to use non-special characters for document IDs. Using special characters you have to be aware of proper URL en-/decoding. Documents prefixed with _ are special documents:
>
>You can have / as part of the document ID but if you refer to a document in a URL you must always encode it as %2F. One special case is _design/ documents, those accept either / or %2F for the / after _design, although / is preferred and %2F is still needed for the rest of the DocID.

**Comment by ahmedyha** [comment]
Fixed in `0.1.6`
