### ISSUE TITLE
Is it possible to get all document that start with perticular word

### ISSUE THREAD

**Issue by jariwalabhavesh** [lightcouch/LightCouch#44]
we know that there is no concept like table in couchdb. record is stored as a document in couchdb.

So i create document id like word_id.

suppose i have docs having _id : Transacation_1,Transacation_2,Transacation_3 and so on.

now how can i get all the documents having _id start with Transacation.

any think is there in lightCouch that can work for it?

**Comment by ahmedyha** [comment]
I don't think there is an API out-of-the-box for this scenario.
It's probably a design decision how to structure documents in CouchDB, instead of documents ids, you may consider emitting one or more keys to identify "Transactions" and leverage the power of Views for query.
