### ISSUE TITLE
Update a document using Lightcouch

### ISSUE THREAD

**Issue by drmencicg** [lightcouch/LightCouch#45]
Hi! I don't understand how to update a Document, I have this code in CouchDB:
    "friends": [
       "martin",
       "maja",
       "damir"
   ],
I was wondering how in android using Lightcouch could I update new friend in friends, I look at Lightcouch API but I have not been success with update. A little example code I beg you, Thanks!

**Comment by ahmedyha** [comment]
Hi

To update a document in CouchDB, usually you will first retrieve the document, modify, then update.

```
Foo foo = dbClient.find(Foo.class, "doc-id");
// .. modify "friends" array or list
dbClient.update(foo);
```

ps. we have a discussion group at http://groups.google.com/group/lightcouch

**Comment by drmencicg** [comment]
OK! Thank You Sir!

**Comment by drmencicg** [comment]
Hi! Can you please reply to this post: https://groups.google.com/forum/#!topic/lightcouch/7GbUjkmVYG0

Thanks!
