### ISSUE TITLE
Wrong url encoding

### ISSUE THREAD

**Issue by iddo** [lightcouch/LightCouch#52]
When querying for a key that includes the plus sign ("+"), it is not encoded into "%2B" and therefore interpreted by CouchDB as a space character.
This is visible in the logs as

`[info] [<0.113.0>] 172.18.0.1 - - GET /dummy/_design/user/_view/phonenumber?include_docs=true&key=%22+972111111111%22 200`

as opposed to the correct url (as is correctly done by the Fauxton interface):

`[info] [<0.103.0>] 172.18.0.1 - - GET /dummy/_design/user/_view/phonenumber?limit=10&reduce=false&key=%22%2B972111111111%22 304`

**Comment by benrudolph** [comment]
I'm also facing this issue. Is there any way to incorporate your latest fix? Is there another workaround? Thanks.

**Comment by lightcouch** [comment]
Hi there,
The fix will be introduced in an imminent release.

**Comment by benrudolph** [comment]
Thanks for the info @lightcouch did that release happen?

**Comment by wpride** [comment]
@lightcouch still running into this issue. Has the fix been released?

**Comment by lightcouch** [comment]
Fixed in release 0.2.0
